# Generated by Django 3.2 on 2022-01-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autopost', '0002_auto_20220128_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledposts',
            name='image',
            field=models.FilePathField(path='img'),
        ),
    ]
