# Generated by Django 3.2 on 2022-01-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autopost', '0003_alter_scheduledposts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledposts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
