# Generated by Django 3.2 on 2022-02-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autopost', '0005_auto_20220201_0520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduledpost',
            options={'ordering': ('-timestamp',), 'verbose_name': 'ScheduledPost', 'verbose_name_plural': 'ScheduledPosts'},
        ),
        migrations.AlterModelOptions(
            name='uploadreport',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AddField(
            model_name='uploadreport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/uploadreport/'),
        ),
    ]
