# Generated by Django 3.2 on 2022-03-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autopost', '0006_auto_20220209_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadreport',
            name='cookies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadreport',
            name='exception',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduledpost',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='uploadreport',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='uploadreport/'),
        ),
    ]
